from pydantic import BaseModel, Field


class QueryExpansionRequest(BaseModel):
    """
    Request for query expansion.
    """

    query: str


class QueryExpansionResponse(BaseModel):
    """
    Expanded search queries generated by the LLM.
    """

    queries: list[str] = Field(
        min_length=1,
        max_length=5,
    )