from enum import Enum


class DepartmentEnum(str, Enum):
    HR = "HR"
    IT_SUPPORT = "IT_SUPPORT"
    ADMIN_FACILITIES = "ADMIN_FACILITIES"
    GENERAL_SUPPORT = "GENERAL_SUPPORT"


class CategoryEnum(str, Enum):

    LEAVE_REQUEST = "LEAVE_REQUEST"
    PAYROLL = "PAYROLL"
    BENEFITS = "BENEFITS"

    VPN_ACCESS = "VPN_ACCESS"
    PASSWORD_RESET = "PASSWORD_RESET"
    SOFTWARE_ISSUE = "SOFTWARE_ISSUE"

    ACCESS_CARD = "ACCESS_CARD"
    MEETING_ROOM = "MEETING_ROOM"
    OFFICE_MAINTENANCE = "OFFICE_MAINTENANCE"
    
    OTHER = "OTHER"

class PriorityEnum(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"