from pydantic import BaseModel
from pydantic import Field

from app.domain.models.chat_message import (
    ChatMessage,
)


class ConversationalQueryExpansionRequest(BaseModel):
    query: str
    conversation_history: list[ChatMessage] = Field(
        default_factory=list,
    )


class ConversationalQueryExpansionResponse(BaseModel):
    """
    Expanded search queries generated by the LLM.
    """

    queries: list[str] = Field(
        min_length=1,
        max_length=5,
    )